name: "Development CI"

on:
  push:
    branches:
      - main

jobs:
  docker-image-build-publish:
    name: Publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Login to Docker hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Get current version
      #   id: get-version
      #   uses: beaconbrigade/package-json-version@v0.3
      #   with:
      #     path: .

      - name: Log in to the github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build docker image
      #   run: docker build -t ghcr.io/${{ github.repository }}/dashboard:v1.x .

      # - name: Push docker image
      #   run: docker push ghcr.io/${{ github.repository }}/dashboard:v1.x

      # - name: Build docker image
      #   run: docker build . --file Dockerfile --tag ruhulinfo/myapp:${{ github.sha }}

      # - name: Push docker image
      #   run: docker push ruhulinfo/myapp:${{ github.sha }}

      - name: Build and push Docker image
        run: |
          docker buildx build --push \
            --tag ghcr.io/${{ github.repository }}/my-image:latest \
            .
        env:
          DOCKER_BUILDKIT: 1
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   uses: docker/setup-buildx-action@v3
      #   with:
      #     context: .
      #     push: true
      #     tags: ghcr.io/${{ github.repository }}/test-image:v1.x
      #   env:
      #     DOCKER_BUILDKIT: 1
      #     GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

